version: '3'

services:
  database:
    image: "postgres" # use latest official postgres version
    container_name: "postgres"
    ports:
      - 5432:5432
    env_file:
      - database.env # configure postgres
    volumes:
      - /Downloads/Estudos/MicronautCacheRedis/dockerVolumes:/var/lib/postgresql/data/ # persist data even if container shuts down

  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"