micronaut:
  application:
    name: micronautCacheRedis
  server:
    port: 8082

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin

jpa:
  default:
    packages-to-scan: com.thais.redis
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

redis:
  uri: redis://localhost
  caches:
    user:
      charset: UTF-8
      value-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
      # expire one hour after write
      expire-after-write: 1h

jackson:
  property-naming-strategy: SNAKE_CASE