micronaut:
  application:
    name: micronautCacheRedis
  server:
    port: 8081

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true